### ISSUE TITLE
CircleCI does not pass on main branch

### ISSUE THREAD

**Issue by evgenyrp** [mozilla/telemetry-batch-view#570]
We can see it passes on pull request:
https://app.circleci.com/pipelines/github/mozilla/telemetry-batch-view/288/workflows/8d9b2f29-14e9-47e1-988e-e97f262c6a05/jobs/2626
but fails on checkout step when it's executing on main branch:
https://app.circleci.com/pipelines/github/mozilla/telemetry-batch-view/289/workflows/d4210539-d870-4c12-b8d3-57043c6a9aac/jobs/2631

```
Using SSH Config Dir '/root/.ssh'
git version 2.11.0
Cloning git repository
Cloning into '.'...
Warning: Permanently added the ECDSA host key for IP address '140.82.112.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

exit status 128
```
It's probably related to branch renaming or a recent update of security policies for github. 

Because of that, the build is not deployed.

I'm not an owner of this repo. @haroldwoo do you have any ideas how to fix this or who can help?

**Comment by haroldwoo** [comment]
After some investigation, it looks like the deployment key got removed somehow (https://github.com/mozilla/telemetry-batch-view/settings/keys).

I generated a new one via circleci's UI 
https://app.circleci.com/settings/project/github/mozilla/telemetry-batch-view/ssh?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fmozilla%2Ftelemetry-batch-view

via mozilla org -> project -> telemetry batch view -> project settings -> SSH Keys. Rm'd the existing one because it no longer showed in github, and regenerated one

**Comment by haroldwoo** [comment]
created https://mozilla-hub.atlassian.net/browse/DSRE-887 for tracking, closing this out

**Comment by evgenyrp** [comment]
> created https://mozilla-hub.atlassian.net/browse/DSRE-887 for tracking, closing this out

Thank you! There's also https://github.com/mozilla/taar_gcp_etl/issues/16 with exactly the same issue.
